---
sidebar: sidebar 
permalink: reference-local-known-limitations.html 
keywords: console local deployment, known limitations, unsupported platforms, unsupported devices, unsupported functions, IP range 
summary: Referência para limitações conhecidas na implantação local do NetApp Console. 
---
= Limitações conhecidas na implantação local do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são compatíveis com esta versão do produto ou que não interoperam corretamente com ela. Analise estas limitações cuidadosamente.



[[console-vm-limitations]]
== Limitações da VM do NetApp Console



[[possible-conflict-with-ip-addresses-in-the-10-42-0-016-and-10-43-0-016-ranges]]
=== Possível conflito com endereços IP nos intervalos 10.42.0.0/16 e 10.43.0.0/16

NetApp Console local deployment utiliza um espaço de endereçamento fixo para a comunicação entre serviços. Os intervalos de endereço IP 10.42.0.0/16 e 10.43.0.0/16 são usados para a rede interna. Antes de implantar o Console local deployment, certifique-se de que esses intervalos de endereço IP não estejam atribuídos a outras VMs, escopos DHCP, registros DNS ou pools de VIP de balanceadores de carga nas VLANs disponibilizadas para o Console local deployment.

Consulte o artigo da Knowledge Base Agent IP conflict with existing network para obter instruções sobre como alterar o endereço IP das interfaces do agente.



[[shared-linux-hosts-are-not-supported]]
=== Hosts Linux compartilhados não são suportados

NetApp Console local não é compatível com uma máquina virtual compartilhada com outros aplicativos. A máquina virtual deve ser dedicada à implantação local do NetApp Console.



[[third-party-agents-and-extensions]]
=== Agentes e extensões de terceiros

Agentes de terceiros ou extensões de VM não são suportados na VM de implantação local do NetApp Console.



[[identity-and-access-limitations]]
== Limitações de identidade e acesso

[cols="1,3"]
|===
| Área | Limitação 


| Integração de usuários locais e recuperação de contas | É necessário configurar um servidor de e-mail SMTP antes de você poder convidar usuários locais ou usar a redefinição de senha para usuários locais. 


| Integração com o Active Directory | Endereços de e-mail duplicados não são suportados entre usuários locais e usuários do Active Directory. Por exemplo, se o administrador local da organização posteriormente se adicionar como um usuário do Active Directory, ele deverá usar um endereço de e-mail diferente. 
|===