---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, phone number, open ticket, web ticket, open an issue 
summary: 'NetApp oferece suporte para NetApp Console implantação local de diversas maneiras. Opções extensas e gratuitas de autoatendimento estão disponíveis 24x7, como artigos da base de conhecimento (KB) e um fórum da comunidade. Seu registro de suporte inclui suporte técnico remoto via sistema de tickets online.' 
---
= Obtenha ajuda com a implantação local do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp oferece suporte para a implantação local do NetApp Console de diversas maneiras. Amplas opções de autossuporte gratuitas estão disponíveis 24x7, como artigos da base de conhecimento (KB) e um fórum da comunidade. Você pode se cadastrar para receber suporte com o número de série de qualquer recurso de armazenamento associado à implantação local do NetApp Console. O cadastro inclui suporte técnico remoto por meio de sistema de tickets online.



[[use-self-support-options]]
== Utilize opções de autoatendimento

Essas opções estão disponíveis gratuitamente, 24 horas por dia, 7 dias por semana:

* Documentação
+
A documentação de implantação local do NetApp Console que você está visualizando no momento.

* https://kb.netapp.com/Cloud/BlueXP["Base de conhecimento"^]
+
Pesquise na NetApp Knowledge Base por artigos que ajudam você a solucionar problemas.





[[open-a-support-case-with-netapp-console-local-deployment]]
== Abra um chamado de suporte com a implantação local do NetApp Console

Abra um chamado de suporte usando um dos números de série do sistema de storage da NetApp gerenciados por meio do seu ambiente de implantação local do NetApp Console.

.Passos
. Acesse  https://mysupport.netapp.com["NetApp site de suporte"^] e faça login com suas credenciais de suporte NetApp.
. Selecione *Casos e peças > Criar caso técnico*.
. Insira o número de série do sistema de storage da NetApp associado ao produto de implantação local do Console que está apresentando o problema.
. Crie um novo caso e selecione o código de categoria apropriado para a implantação local do NetApp Console.




[[download-a-support-bundle]]
== Baixe um pacote de suporte

Um pacote de suporte inclui registros recentes e informações de configuração. Você pode baixar o pacote mais recente e enviá-lo ao suporte técnico da NetApp caso seja solicitado.

.Passos
. Selecione *Administração > Suporte* para visualizar a página de Suporte.
. No cartão de suporte, selecione *Criar* para criar um pacote de logs e dados de configuração.
. Após a criação do pacote, selecione *Download*. Você será solicitado a baixar um arquivo ZIP.
+
O sistema mantém apenas um pacote por vez. A criação de um novo pacote de suporte substitui o anterior.


