= 
:allow-uri-read: 


Após instalar e configurar o agente do NetApp Console, adicione suas credenciais de nuvem para que o agente do NetApp Console tenha as permissões necessárias para executar ações na Amazon Web Services ou no Microsoft Azure.

[role="tabbed-block"]
====
.AWS
--
.Antes de começar
Se você acabou de criar essas credenciais da AWS, elas podem levar alguns minutos para ficarem disponíveis. Aguarde alguns minutos antes de adicionar as credenciais ao Console.

.Passos
. Selecione *Administração > Credenciais*.
. Selecione *Credenciais da organização*.
. Selecione *Adicionar credenciais* e siga os passos do assistente.
+
.. *Localização das credenciais*: selecione *Amazon Web Services > Agente.
.. *Definir credenciais*: Insira uma chave de acesso e uma chave secreta da AWS.
.. *Assinatura do Marketplace*: associe uma assinatura do Marketplace a estas credenciais, assinando agora ou selecionando uma assinatura existente.
.. *Revisar*: confirme os detalhes das novas credenciais e selecione *Adicionar*.




Agora você pode acessar o  https://console.netapp.com["NetApp Console"^] para começar a usar o agente do NetApp Console.

--
.Azure
--
.Antes de começar
Se você acabou de criar essas credenciais do Azure, elas podem levar alguns minutos para ficarem disponíveis. Aguarde alguns minutos antes de adicionar as credenciais ao agente do Console.

.Passos
. Selecione *Administração > Credenciais*.
. Selecione *Adicionar credenciais* e siga os passos do assistente.
+
.. *Localização das credenciais*: Selecione *Microsoft Azure > Agent*.
.. *Definir credenciais*: insira informações sobre a entidade de serviço do Microsoft Entra que concede as permissões necessárias:
+
*** ID do aplicativo (cliente)
*** ID do diretório (tenant)
*** Segredo do cliente


.. *Assinatura do Marketplace*: associe uma assinatura do Marketplace a estas credenciais, assinando agora ou selecionando uma assinatura existente.
.. *Revisar*: confirme os detalhes das novas credenciais e selecione *Adicionar*.




.Resultado
O agente do Console agora possui as permissões necessárias para executar ações no Azure em seu nome. Agora você pode acessar o  https://console.netapp.com["NetApp Console"^] para começar a usar o agente do Console.

--
====