= 
:allow-uri-read: 


Crie uma função e aplique-a a uma conta de serviço que você usará para a instância de máquina virtual do agente do Console.

.Passos
. Crie uma função personalizada no Google Cloud:
+
.. Crie um arquivo YAML que inclua as permissões definidas no link:reference-permissions-gcp.html["Política de agente do Console para o Google Cloud"].
.. No Google Cloud, ative o cloud shell.
.. Faça o upload do arquivo YAML que inclui as permissões necessárias para o agente do Console.
.. Crie uma função personalizada usando o comando  `gcloud iam roles create`.
+
O exemplo a seguir cria uma função chamada "connector" no nível do projeto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentação do Google Cloud: criando e gerenciando funções personalizadas"^]



. Crie uma conta de serviço no Google Cloud:
+
.. No serviço IAM & Admin, selecione *Service Accounts > Create Service Account*.
.. Insira os detalhes da conta de serviço e selecione *Criar e Continuar*.
.. Selecione a função que você acabou de criar.
.. Conclua as etapas restantes para criar a função.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentação do Google Cloud: criando uma conta de serviço"^]





.Resultado
Agora você tem uma conta de serviço que pode atribuir à instância de máquina virtual do agente do Console.
