= 
:allow-uri-read: 


.Antes de começar
Você deve ter o seguinte:

* Privilégios de root para instalar o agente.
* Detalhes sobre um servidor proxy, caso seja necessário um proxy para acesso à internet do agente.
+
Você tem a opção de configurar um servidor proxy após a instalação, mas isso requer a reinicialização do agente.

* Um certificado assinado por uma Autoridade Certificadora (CA), caso o servidor proxy utilize HTTPS ou se o proxy seja um proxy interceptador.


.Sobre esta tarefa
O instalador disponível no NetApp site de suporte pode ser uma versão anterior. Após a instalação, o agente se atualiza automaticamente caso uma nova versão esteja disponível.

.Passos
. Se as variáveis de sistema _http_proxy_ ou _https_proxy_ estiverem definidas no host, remova-as:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se você não remover essas variáveis de sistema, a instalação falhará.

. Baixe o software do agente do  https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp site de suporte"^] e, em seguida, copie-o para o host Linux.
+
Você deve baixar o instalador do agente "online" destinado ao uso em sua rede ou na nuvem.

. Atribua permissões para executar o script.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Onde <version> é a versão do agente que você baixou.

. Execute o script de instalação.
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Os parâmetros --proxy e --cacert são opcionais. Se você tiver um servidor proxy, você precisará inserir os parâmetros conforme mostrado. O instalador não solicita que você forneça informações sobre um servidor proxy.

+
Aqui está um exemplo do comando usando ambos os parâmetros opcionais:

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
A opção --proxy configura o agente para usar um servidor proxy HTTP ou HTTPS usando um dos seguintes formatos:

+
** \http://endereço:port
** \http://nome-de-usuário:senha@endereço:port
** \http://nome-do-domínio%92nome-de-usuário:senha@endereço:porta
** \https://endereço:port
** \https://nome-de-usuário:senha@endereço:porta
** \https://nome-do-domínio%92nome-de-usuário:senha@endereço:porta
+
Observe o seguinte:

+
*** O usuário pode ser um usuário local ou um usuário de domínio.
*** Para um usuário de domínio, você deve usar o código ASCII para uma barra invertida (\), conforme mostrado acima.
*** O agente não suporta nomes de usuário ou senhas que incluam o caractere @.
*** Se a senha incluir algum dos seguintes caracteres especiais, você deve escapar esse caractere especial adicionando uma barra invertida antes dele: & ou !
+
Por exemplo:

+
\http://bxpproxyuser:netapp1\!@address:3128





+
O parâmetro `--cacert` especifica um certificado assinado por uma Autoridade Certificadora (CA) para ser usado no acesso HTTPS entre o agente e o servidor proxy. Este parâmetro é necessário apenas se você especificar um servidor proxy HTTPS ou se o proxy for um proxy interceptador.

. Se você usou o Podman, precisará ajustar a porta do aardvark-dns.
+
.. Conecte-se via SSH à máquina virtual do agente.
.. Abra o arquivo podman _/usr/share/containers/containers.conf_ e modifique a porta escolhida para o serviço DNS. Por exemplo, altere para 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Reinicie a máquina virtual do agente.




. Aguarde a conclusão da instalação.
+
Ao final da instalação, o serviço do agente (occm) reinicia duas vezes se você especificou um servidor proxy.

. Abra um navegador da web em um host que tenha conexão com a máquina virtual do agente e digite o seguinte URL:
+
https://_ipaddress_[]

. Após efetuar o login, configure o agente:
+
.. Especifique a organização do Console a ser associada ao agente.
.. Insira um nome para o sistema.
.. Em *Você está executando em um ambiente seguro?* mantenha o modo restrito desativado.
+
Você deve manter o modo restrito desativado porque estas etapas descrevem como usar o Console no modo padrão. Você deve ativar o modo restrito somente se tiver um ambiente seguro e quiser desconectar esta conta dos serviços de backend do Console. Se for esse o caso, link:task-quick-start-restricted-mode.html["Siga os passos para começar a usar o NetApp Console no modo restrito"].

.. Selecione *Vamos começar*.



